### ISSUE TITLE
Can't extract .arc files

### ISSUE THREAD

**Issue by SamusAranX** [McKay42/mph-arc-extractor#1]
```
PS C:\Users\Peter\Desktop\MPH.Model.Viewer\MPH Model Viewer\mph\models> .\mpharc.exe .\bigeyeroom.arc
ERROR: Invalid numfiles in header (1179208773)
ERROR: load() a file before trying to extract it.
```

I'm not sure what's going on here. I know this used to work, but for some reason it doesn't anymore.
Any thoughts on what I might be doing wrong here?

**Comment by McKay42** [comment]
When extracting the initial files from an nds rom, you must use something like [Tahaxan/Tihaxa](http://gbatemp.net/t291274-the-ultimate-nintendo-ds-rom-hacking-guide) which supports decompression, see https://imgur.com/a/LyeJUna

Afterwards, the extracted and decompressed mph arc files can then be further extracted with mpharc.
(mpharc _only_ works for mph, no other games are supported. Use JoeBlob's [arcman](http://gbatemp.net/t291274-the-ultimate-nintendo-ds-rom-hacking-guide) for non-mph arc files.)
